### ISSUE TITLE
List Index out of range

### ISSUE THREAD

**Issue by waynemaclaurin** [mikemountain/nfl-led-scoreboard#39]
Scoreboard has been working great.  No changes, but suddenly started throwing "list index out of range"

sudo python main.py --led-gpio-mapping=adafruit-hat-pwm --led-brightness=60 --led-slowdown-gpio=2
INFO (09:26:09): NFL Scoreboard - v1.0.0 (64x32)
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    MainRenderer(matrix, data).render()
  File "/home/pi/nfl-led-scoreboard/renderer/main.py", line 32, in render
    self.__render_game()
  File "/home/pi/nfl-led-scoreboard/renderer/main.py", line 41, in __render_game
    self.__draw_game(self.data.current_game())
  File "/home/pi/nfl-led-scoreboard/data/data.py", line 79, in current_game
    return self.games[self.current_game_index]
IndexError: list index out of range

Running on a Pi 3B,  64x32 display,  and a piHat ..  

Any thoughts ?

**Comment by waynemaclaurin** [comment]
ended up just rebuilding from scratch and everything is back to normal ... odd
