### ISSUE TITLE
ModuleNotFoundError: No module named 'nfl_api_parser'

### ISSUE THREAD

**Issue by Jordinho** [mikemountain/nfl-led-scoreboard#42]
For some reason it seems like data.py isn't able to import nfl_api_parser when I run main.py

I have installed the NHL and other programs like this before and not had an issue.  Have you seen this before?

sudo python main.py --led-gpio-mapping=ada fruit-hat-pwm --led-brightness=60 --led-slowdown-gpio=2
/home/pi/nfl-led-scoreboard/renderer/main.py:365: SyntaxWarning: "is not" with a                                                        literal. Did you mean "!="?
  while x is not 3:
/home/pi/nfl-led-scoreboard/renderer/main.py:377: SyntaxWarning: "is not" with a                                                        literal. Did you mean "!="?
  while x is not 3:
/home/pi/nfl-led-scoreboard/renderer/main.py:398: SyntaxWarning: "is not" with a                                                        literal. Did you mean "!="?
  while x is not 3:
Traceback (most recent call last):
  File "/home/pi/nfl-led-scoreboard/main.py", line 6, in <module>
    from data.data import Data
  File "/home/pi/nfl-led-scoreboard/data/data.py", line 3, in <module>
    import nfl_api_parser as nflparser
ModuleNotFoundError: No module named 'nfl_api_parser'

**Comment by MedizinPumPer** [comment]
go to "data"->"data.py" and add "data." before the nfl_api_parser that it looks like "data.nfl_api_parser"
